# Generated by Django 4.1.7 on 2023-03-24 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
